### ISSUE TITLE
DB Init

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-directory#6]
- [x] adopt `DbInitializer` from "that other place it's in";
- [x] modify it, so it does not recompute views on formatting changes;
- [ ] make independent, maybe move out to its own place.

**Comment by elmigranto** [comment]
So I pushed this into #2 with couple of changes from what we had previously:
  - couch stores contents of the file (`*.design.js`), and we compare that instead of individual functions — so we don't have to redo views if v8 changes `.toString()` for functions;
  - if things are out of sync (missing db, or changed/missing view), it will fail with error unless ran with flag `--sync-db`.

Let me know in case any of these do not sound right. (I am not sure about 2nd point.)

**Comment by j3k0** [comment]
Excellent!

Indeed it a far better solution than what we had so far. The sync-db flag is great, I'd rather have a deploy fail than upgrading views without my consent (generally at the worst possible moment).

A little request, make `--sync-db` an environment variable (it's easier when deploying with mesos/marathon).

BTW, that gave me got a cool idea (my dream DbInitializer). Let me know if that's easy. If we got the design doc name in a env variable, this would allow to deploy an upgrade of the module without stopping the older version (i.e. without interruption of service).

Use case:
 * Current deployment has env `DEPLOYMENT_VIEW=directory1`.
 * Deployment of an upgrade fails because view need update.
 * We start a new deploy with env `SYNC_DB=1` and `DIRECTORY_VIEW=directory2`.

This way we can keep the old version running while the views for the upgrade are being computed.

Also, for practical reasons, with `SYNC_DB=1` (or --sync-db) the server should just trigger the db update and not take any request (maybe that's what you did already?).

What do you think?

**Comment by elmigranto** [comment]
1. Env vars — should be easy change, both design name and sync_db part.
  1. "Sync db does not accept requests" — do you mean run it like a script (upgrade and exit) or start upgrading, when it's done start accepting requests (that's how it works — master checks/syncs db and, after that succeeded, forks).

**Comment by j3k0** [comment]
> start upgrading, when it's done start accepting requests

Do you mean after changing the design document, or after the view is done being computed? Changing the design document will return success immediately, updating the view might take hours.

If I'm right, to know that a view is done being computed you need to check with couchdb's `/_active_tasks` endpoint (`nano` might have an access method to this)... Anyway, if you're not already doing that: it's fine to run with `--sync-db` as a script (exit right away)

**Comment by elmigranto** [comment]
No, it simply replaces design documents and starts doing things, it won't wait for recompute (also, I believe you have to trigger recompute by accessing something view-related, simply replacing document won't start it, no?).

So, currently:
  - start process;
  - check if db is synced, if not, replace documents or die (depending on `SYNC_DB` presence);
  - `fork()` some workers.

Instead we want:
  - start process;
  - check db:
    - everything's the same — `fork()` worker
    - something changed/missing
      - No `SYNC_DB` -> die;
      - `SYNC_DB` present: 
        - sync database
        - trigger recompute
        - start polling for completion, exit when done.

**Comment by elmigranto** [comment]
Or do we want second flow, but instead of exiting, it `fork()`s on completion?

**Comment by elmigranto** [comment]
I think it would be best to just replace documents, trigger update and exit. I don't think there is much point in waiting to compleition in either case without making things too complicated. After all, there is not much difference between timeout due to view being calculated or 503 not available. And we are answering from older version anyways, so…

Though it would be neat to know just the moment for when it's safe to switch from DESIGN1 to DESIGN2, I don't think it is that crucial.

**Comment by j3k0** [comment]
Agreed, no need to get into complicated logic. Just exit (after update design doc) when SYNC_DB is present, not without a read access to the view to make sure it's being computed.
